name: integrazoo
description: "A project for collecting bovine data."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  fl_chart: ^0.67.0

  intl: ^0.19.0

  path: ^1.9.0

  sqflite: ^2.3.2

  drift: ^2.21.0
  drift_flutter: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  test: ^1.16.0

  sqflite_common_ffi: ^2.3.4
  drift_dev: ^2.21.2

  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/icons/bull-head.png
    - assets/icons/cow-head.png
